---
# This playbook tests the script module on Windows hosts

- name: Run powershell script
  hosts: localhost 
  gather_facts: false
  tasks:
    - name: Run powershell script
      command: pwsh hello.ps1
