
---
- name: Playbook for cmd poweshell
  hosts: localhost

  tasks:
    - name: Checking For PowerCLI Module
      shell: pwsh Import-Module -Name VMware.PowerCLI
      register: _powercli_module
      failed_when: false
      changed_when: false

