
---
- name: Playbook for cmd poweshell
  hosts: localhost

  tasks:
 #   - name: Checking For PowerCLI Module
 #shell: pwsh -Command Install-Module "VMware.PowerCLI" -Scope "AllUsers" -AllowClobber -Force
    - name: Checking For PowerCLI Module
      shell: pwsh -Command Import-Module -Name VMware.PowerCLI
      register: _powercli_module
      failed_when: false
      changed_when: false
    - name: Disable Invalid Cert Warning For PowerCLI
      shell: echo Y | pwsh -Command Set-PowerCLIConfiguration -InvalidCertificateAction ignore
    - name: PS1 file execution
      script: vminfo.ps1
      args:
        executable: /usr/bin/pwsh
      register: output 
